### ISSUE TITLE
Missing USB file write events

### ISSUE THREAD

**Issue by gunnahafta** [microsoft/WindowsDefenderATP-Hunting-Queries#108]
I have been using the below query (with some lens commented out) to try and capture files being written to USB.

However knowing that some people wrote to USB they didn't show up with this query.  I can prvide this with a simple query loking for filecreation on a folderpath containing "D:" (i know the USB drive was a D drive) and I get the expected results.

I did some searching and it seems the action type "UsbDriveMount" is the problem.  I find that it doesn't pick up everything and sometimes I have to use ActionType == "PnpDeviceConnected".  Problem is PnpDeviceConnected picks up a whole lot of pnp devices.  How can I ensure that this query is getting all USB storage devices.  Right now i am not confident it is.

// THIS IS THE FIRST QUERY
DeviceEvents
| where Timestamp > ago(90d)
| where ActionType == "UsbDriveMount"
| project USBMountTime = Timestamp, DeviceId, AdditionalFields
| extend DriveLetter = tostring(todynamic(AdditionalFields).DriveLetter)
| join (
DeviceFileEvents
| where Timestamp > ago(90d)
| where ActionType == "FileCreated"
// | where FileName endswith ".docx" or FileName endswith ".pptx"
| parse FolderPath with DriveLetter '\\' *
| extend DriveLetter = tostring(DriveLetter)
)
on DeviceId, DriveLetter
// | where (Timestamp - USBMountTime) between (0min .. 15min)
| summarize DistinctFilesCopied = dcount(SHA1), Events=makeset(pack("AccountName", InitiatingProcessAccountName, "Timestamp", Timestamp, "ReportId", ReportId, "FileName", FileName, "AdditionalDriveProperties", AdditionalFields)) by DeviceId, bin(Timestamp, 15m)
// | where DistinctFilesCopied > 10
| mv-expand Events
| extend Timestamp = todatetime(Events.Timestamp), FileName = Events.FileName, AccountName = Events.AccountName, ReportId = tolong(Events.ReportId), AdditionalDriveProperties = Events.AdditionalDriveProperties

**Comment by iadgovuser1** [comment]
@gunnahafta 

Here's an example that could filter on USB storage when using PnpDeviceConnected.

DeviceEvents
| project Timestamp, DeviceName, ActionType, AdditionalFields  
| where ActionType == 'PnpDeviceConnected'
| extend PNP = parsejson(AdditionalFields) 
| extend ClassName = PNP.ClassName 
| extend DeviceId = PNP.DeviceId 
| extend DeviceDescription = PNP.DeviceDescription
| extend VendorId = PNP.VendorIds
| where DeviceId startswith @'USBSTOR\'
| project-away ActionType, AdditionalFields, PNP
| sort by Timestamp desc

**Comment by gunnahafta** [comment]
Thanks.  Question about detecting USB drives in general, if I had a USB stick in a dock and I was regularly taking my laptop on and off the dock would this show up as a USB stick detected each time i reconnect to the dock which has the USB stick connected?

**Comment by iadgovuser1** [comment]
@gunnahafta Hard to say. Probably varies based on manufacturer. The dock might have a USB hub in it.
