### ISSUE TITLE
Unable to query events from prior than 7 days

### ISSUE THREAD

**Issue by DSharpPro** [microsoft/WindowsDefenderATP-Hunting-Queries#94]
Hi,

When running a query the console only enabled the viewing of the past 7 days even if its been specified differently within the query itself. I am trying to create a query that shows how many incidents are being created on a monthly basis to confirm if securing our systems is improving or not.

Thank you

**Comment by iadgovuser1** [comment]
The upper right corner of the Advanced Hunting query dialog has a day selection that is set to 7 days by default. That must override what you specify in the query (if you specif anything at all).
